"""Refresh factual NARO palette records; never execute downloaded JavaScript.

Only class codes/names and RGB keys are retained, not the site's application code.
Released soil maps: CC BY 4.0; see docs/soil-method.md and docs/data-sources.md.
"""
import hashlib
import json
from pathlib import Path
import re
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[2]
SOURCES = {
    'classes': 'https://soil-inventory.rad.naro.go.jp/main/static/apac/figureRGB.js',
    'textures': 'https://soil-inventory.rad.naro.go.jp/main/static/apac/chRGB.js',
}


def records(text, variable):
    text = re.sub(r'/\*[\s\S]*?\*/', '', text)
    text = re.sub(r'(?m)^\s*//.*$', '', text)
    match = re.search(r'var\s+' + variable + r'\s*=\s*(\[[\s\S]*?\]);', text)
    if not match:
        raise ValueError('Official palette format changed: ' + variable)
    # This known source table contains JSON-compatible literals and trailing commas.
    return json.loads(re.sub(r',\s*([\]}])', r'\1', match[1]))


def main():
    raw = {key: urlopen(url, timeout=30).read() for key, url in SOURCES.items()}
    classes = [row[:5] for row in records(raw['classes'].decode('utf-8-sig'), 'figureRGB')]
    textures = records(raw['textures'].decode('utf-8-sig'), 'texturergb')
    for rows in [classes, textures]:
        seen = {}
        for row in rows:
            if any(not isinstance(v, int) or not 0 <= v <= 255 for v in row[:3]):
                raise ValueError('Invalid RGB key')
            key = tuple(row[:3])
            if key in seen and row != seen[key]:
                raise ValueError('Ambiguous official RGB key')
            seen[key] = row
        rows[:] = seen.values()
    if len(classes) < 500 or len(textures) != 9:
        raise ValueError('Unexpected palette size; review source changes manually')
    metadata = {key: {'url': SOURCES[key], 'sha256': hashlib.sha256(data).hexdigest()}
                for key, data in raw.items()}
    output = '// Generated by scripts/soil/update_catalog.py. NARO Japanese Soil Inventory; CC BY 4.0.\n'
    for name, value in [('SOIL_CATALOG_SOURCES', metadata), ('SOIL_CLASSES', classes), ('SOIL_TEXTURES', textures)]:
        output += 'export const ' + name + '=' + json.dumps(value, ensure_ascii=False, separators=(',', ':')) + ';\n'
    path = ROOT / 'dist/gis/soil-catalog.mjs'
    path.write_text(output, encoding='utf-8')
    print(f'Wrote {len(classes)} classes and {len(textures)} textures to {path.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
